version: '2.1'

services:

  redis:
    image: "redis:latest"
    ports:
      - 6379:6379


  openresty1:
    image: "openresty/openresty:latest"
    ports:
      - 8081:80
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:rw
      - ./logs:/usr/local/openresty/nginx/logs:rw
      - ./html:/usr/local/openresty/nginx/html:rw
      - ./lua:/usr/local/openresty/nginx/lua:rw

  openresty2:
    image: openresty/openresty:latest
    ports:
      - 8082:80
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:rw
      - ./logs:/usr/local/openresty/nginx/logs:rw
      - ./html:/usr/local/openresty/nginx/html:rw
      - ./lua:/usr/local/openresty/nginx/lua:rw