version: '3'

services:

  redis:
    image: "redis:alpine"
    container_name: redis_db #指定后无法用scale命令
    restart: always
    networks: 
      - backend


  nginx_server:
    image: "openresty/openresty:latest"
    container_name: nginx_lua
    ports:
      - "80:80"
    volumes:
      - ${HOST_DIR}/conf/nginx.conf:${CONTAINER_DIR}/conf/nginx.conf:rw
      - ${HOST_DIR}/logs:${CONTAINER_DIR}/logs:rw
      - ${HOST_DIR}/html:${CONTAINER_DIR}/html:rw
      - ${HOST_DIR}/lua:${CONTAINER_DIR}/lua:rw
    depends_on:
      - redis
    environment:
        - NAME=LPC
    networks: 
      - default
      - backend

networks:
  default:
    driver: bridge
  backend:
    driver: bridge